### ISSUE TITLE
[Idea] GameObject Notes

### ISSUE THREAD

**Issue by borntocompile** [dubit/duck-packages#3]
The ability to add a note/comment to a gameObject in the scene or as a prefab to provide extra information inside the engine and attach to the specific gameObject.

* The note should not be serialized with the gameObject.
* Ability to add, remove or edit notes.
* Note types, standard and TODO
* Serialized as a ScriptableObject inside an Editor folder to avoid adding these development notes to the build.

Complexity:
* To attach a note to a gameObject requires a CustomInspector. The common component between all GameObjects is Transform. To create a custom inspector for Transform means loss of the built in Unity custom inspector. However you can mimic the unity inspector (http://wiki.unity3d.com/index.php/TransformInspector) and then add the Notes in there too.

**Comment by MagicMatt** [comment]
How does the Transform get added to all GameObjects? Could we just add a notes component?
